spring:
  datasource:
    url: jdbc:mysql://192.168.0.111:3306/nimbleorm?useCursorFetch=true&serverTimezone=GMT%2B8
    username: dev
    password: devdev
    driver-class-name: com.mysql.cj.jdbc.Driver